'use strict'

var $ = require('jquery')
var onWindowResize = require('./events/onWindowResize')
var onClickUndelete = require('./events/onClickUndelete')
var onKeydownSuchen = require('./events/menu/onKeydownSuchen')
var onClickExportieren = require('./events/menu/onClickExportieren')
var onClickProgrammWahl = require('./events/menu/onClickProgrammWahl')
var onClickApLoeschen = require('./events/menu/onClickApLoeschen')
var onChangeApWaehlen = require('./events/menu/onChangeApWaehlen')
var onChangeEwmsApWaehlen = require('./events/menu/onChangeEwmsApWaehlen')
var onClickApWaehlenTextLoeschen = require('./events/menu/onClickApWaehlenTextLoeschen')
var onClickEwmsApWaehlenTextLoeschen = require('./events/menu/onClickEwmsApWaehlenTextLoeschen')
var onKeyupClickSuchen = require('./events/menu/onKeyupClickSuchen')
var onKeydownForm = require('./events/forms/onKeydownForm')
var onChangeSpeichern = require('./events/forms/onChangeSpeichern')
var onClickKopiereKoordinatenInPop = require('./events/forms/onClickKopiereKoordinatenInPop')
var onClickGuid = require('./events/forms/onClickGuid')
var onKeyupFocusTextarea = require('./events/forms/onKeyupFocusTextarea')
var onClickExportPop = require('./events/forms/onClickExportPop')
var onClickExportKontr = require('./events/forms/onClickExportKontr')
var onClickExportTpop = require('./events/forms/onClickExportTpop')
var onClickExportTpopMassn = require('./events/forms/onClickExportTpopMassn')
var onChangeBerUrl = require('./events/forms/onChangeBerUrl')
var onClickExport = require('./events/forms/onClickExport')
var onClickExportDatenstrukturGrafisch = require('./events/forms/onClickExportDatenstrukturGrafisch')
var onClickOlMapExportieren = require('./events/forms/olMap/onClickOlMapExportieren')
var onClickOlmapLayertreeCheckbox = require('./events/forms/olMap/layertree/onClickOlmapLayertreeCheckbox')
var onClickLayertreePopStyle = require('./events/forms/olMap/layertree/onClickLayertreePopStyle')
var onClickLayertreeTpopStyle = require('./events/forms/olMap/layertree/onClickLayertreeTpopStyle')
var onClickModifyLayer = require('./events/forms/olMap/layertree/onClickModifyLayer')
var onClickRenameLayer = require('./events/forms/olMap/layertree/onClickRenameLayer')
var onClickEntferneLayer = require('./events/forms/olMap/layertree/onClickEntferneLayer')
var onClickNeuesLayer = require('./events/forms/olMap/layertree/onClickNeuesLayer')
var onClickErgebnisAuswahlClose = require('./events/forms/olMap/onClickErgebnisAuswahlClose')
var onClickGMapDistanzMessen = require('./events/forms/gMap/onClickGMapDistanzMessen')
var onClickGMapDistanzMessenEntfernen = require('./events/forms/gMap/onClickGMapDistanzMessenEntfernen')
var onClickDetailplaeneCheckbox = require('./events/forms/gMap/onClickDetailplaeneCheckbox')
var onSelectmenuchangeExportLayerSelect = require('./events/forms/olMap/layertree/onSelectmenuchangeExportLayerSelect')
var onClickQkSort = require('./events/forms/onClickQkSort')
var onChangeQkBerichtjahr = require('./events/forms/onChangeQkBerichtjahr')
var onClickQkSearchEmpty = require('./events/forms/onClickQkSearchEmpty')
var onClickQkRefresh = require('./events/forms/onClickQkRefresh')
var onMousewheelNumber = require('./events/onMousewheelNumber')

module.exports = function () {
  $(window).resize(onWindowResize)
  $('#undeleteDiv')
    .on('click', '.undeleteLink', onClickUndelete)

  $('#menu')
    .on('click', '.exportieren', onClickExportieren)
    .on('click', '[name=programmWahl]', onClickProgrammWahl)
  $('#apLoeschen')
    .on('click', onClickApLoeschen)
  $('#apWaehlen')
    .on('change', onChangeApWaehlen)
  $('#ewmsApWaehlen')
    .on('change', onChangeEwmsApWaehlen)
  $('#apWaehlenTextLoeschen')
    .on('click', onClickApWaehlenTextLoeschen)
  $('#ewmsApWaehlenTextLoeschen')
    .on('click', onClickEwmsApWaehlenTextLoeschen)
  $('#suchen')
    .on('keydown', onKeydownSuchen)
    .on('keyup click', onKeyupClickSuchen)

  $('#forms')
    .on('keydown', onKeydownForm)
    .on('click', '.guid', onClickGuid)
    .on('click', '.exportPop', onClickExportPop)
    .on('click', '.exportKontr', onClickExportKontr)
    .on('click', '.exportTpop', onClickExportTpop)
    .on('click', '.exportMassn', onClickExportTpopMassn)
  $('.form')
    .on('change', '.speichern', onChangeSpeichern)
    .on('keyup focus', 'textarea', onKeyupFocusTextarea)
  $('#kopiereKoordinatenInPop')
    .on('click', onClickKopiereKoordinatenInPop)

  $('#qualitaetskontrollen')
    .on('click', '.sort', onClickQkSort)
    .on('click', '#qkSearchEmpty', onClickQkSearchEmpty)
    .on('click', '.qkRefresh', onClickQkRefresh)
    .on('change', '#qkBerichtjahr', onChangeQkBerichtjahr)

  $('#olMapExportieren')
    .on('click', onClickOlMapExportieren)
  $('#olMapLayertree')
    .on('click', '.olmapLayertreeCheckbox', onClickOlmapLayertreeCheckbox)
    .on('click', '.layertreePopStyle', onClickLayertreePopStyle)
    .on('click', '.layertreeTpopStyle', onClickLayertreeTpopStyle)
    .on('click', '.modifyLayer', onClickModifyLayer)
    .on('selectmenuchange', '.exportLayerSelect', onSelectmenuchangeExportLayerSelect)
    .on('click', '.renameLayer', onClickRenameLayer)
    .on('click', '.entferneLayer', onClickEntferneLayer)
    .on('click', '.neuesLayer', onClickNeuesLayer)
  $('#olMapErgebnisAuswahlHeader')
    .on('click', '.ui-icon.ui-icon-closethick', onClickErgebnisAuswahlClose)

  $('#gMapDetailplaeneCheckbox')
    .on('click', onClickDetailplaeneCheckbox)
  $('#gMapDistanzMessen')
    .on('click', onClickGMapDistanzMessen)
  $('#gMapDistanzMessenEntfernen')
    .on('click', onClickGMapDistanzMessenEntfernen)

  $('#BerURL')
    .on('change', onChangeBerUrl)

  $('#exporte')
    .on('click', '.export', onClickExport)
  $('#exportDatenstrukturGrafisch')
    .on('click', onClickExportDatenstrukturGrafisch)

  // verhindern, dass Zahlen durch Scrollen am Mausrad aus Versehen verändert werden
  $('body').on('mousewheel', '[type="number"]', onMousewheelNumber)
}
